name: CI
on: [push, pull_request, workflow_dispatch]
env:
  ProjectName: WinUITemplate

jobs:
  check_format:
    name: Check format
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run dotnet format check
        run: dotnet format -v diag --verify-no-changes
